apiVersion: batch/v1
kind: Job
metadata:
  name: dokh-objarverse-splitdf
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      schedulerName: volcano
      restartPolicy: Never
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: objarverse-raw
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 256Gi
      containers:
      - name: objarverse-splitdf
        image: kohido/3d_dl_cuda129:v0.0.3
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        command: ["bash","-lc"]
        args:
        - |
          set -e
          cd /mnt/data
          if [ -d "3ddata" ]; then
            cd 3ddata
            git pull
          else
            git clone https://github.com/trinity-graphics/3ddata.git
            cd 3ddata/
          fi
          cd objarverse/download_script
          bash run.sh obj

        volumeMounts:
        - {name: data, mountPath: /mnt/data}
        - {name: dshm, mountPath: /dev/shm}
        resources:
          limits:   { cpu: "48",  memory: "256Gi" }
          requests: { cpu: "48",  memory: "256Gi" }