apiVersion: batch/v1
kind: Job
metadata:
  name: dokh-objarverse-download-ply
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      schedulerName: volcano
      restartPolicy: Never
      volumes:
      - name: project
        persistentVolumeClaim:
          claimName: prj-0
      - name: data
        persistentVolumeClaim:
          claimName: objarverse-raw
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 256Gi
      containers:
      - name: objarverse-download-ply
        image: kohido/3d_dl_cuda129:v0.0.3
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: dokh-secret
              key: GITHUB_TOKEN
        command: ["bash","-lc"]
        args:
        - |
          set -e
          cd /mnt/prj/
          if [ -d "3ddata" ]; then
            cd 3ddata
            git pull
          else
            git clone https://github.com/trinity-graphics/3ddata.git
            cd 3ddata/
          fi
          cd objarverse/download_script
          curl -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/rate_limit
          curl -I https://api.github.com/users/octocat
          bash run.sh ply

        volumeMounts:
        - {name: project, mountPath: /mnt/prj/}
        - {name: data, mountPath: /mnt/data}
        - {name: dshm, mountPath: /dev/shm}
        resources:
          limits:   { cpu: "16",  memory: "64Gi" }
          requests: { cpu: "16",  memory: "64Gi" }